import Footer from "@/components/Footer/Footer";
import Navigation from "@/components/Navigation/Navigation";
import { Inter } from "next/font/google";
import { Providers } from "./store/provider";
import AuthProvider from "@/providers/AuthProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="overlays"></div>
        <AuthProvider>
          <Providers>
            <Navigation />
            {children}
            <Footer />
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
